name: hamiguitan_trekscan_plus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^3.4.1
  permission_handler: ^11.3.1
  permission_handler_android: ^12.0.0
  shared_preferences: ^2.2.2
  file_picker: ^10.3.3
  firebase_core: ^2.13.0
  firebase_auth: ^4.10.0
  google_sign_in: ^5.4.4
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.3.0
  firebase_app_check: ^0.2.2
  firebase_messaging: ^14.6.0
  flutter_local_notifications: ^17.0.0
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  geolocator: ^9.0.2
  image: ^4.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  mailer: ^6.0.1
  flutter_dotenv: ^5.1.0
  app_links: ^6.4.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.3
  provider: ^6.0.0
  uuid: ^4.5.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/station_images/Black Mountain/
    - assets/station_images/Camp 3/
    - assets/station_images/Camp 4/
    - assets/station_images/Crossing Stampa/
    - assets/station_images/Hidden Garden/
    - assets/station_images/Lantawan 1/
    - assets/station_images/Lantawan 2/
    - assets/station_images/Lantawan 3/
    - assets/station_images/Leptospermum amboinense/
    - assets/station_images/Mossy Forest/
    - assets/station_images/Nepenthes micromphora/
    - assets/station_images/Nephentes hamiguiteneses/
    - assets/station_images/Nephentes peltata/
    - assets/station_images/Puting Bato/
    - assets/station_images/Pygmy Field/
    - assets/station_images/The Peak/
    - assets/station_images/Tinagong Dagat/
    - assets/station_images/Twin Falls/
    - assets/station_images/UNESCO Marker/
    - assets/station_images/Uwang-Uwang/
    - assets/icons/
    - assets/data/
    - assets/data/badge.json
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MONTSERRAT-REGULAR.ttf
        - asset: assets/fonts/MONTSERRAT-BOLD.ttf
          weight: 700
        - asset: assets/fonts/MONTSERRAT-SEMIBOLD.ttf
          weight: 600
        - asset: assets/fonts/MONTSERRAT-LIGHT.ttf
          weight: 300
        - asset: assets/fonts/MONTSERRAT-MEDIUM.ttf
          weight: 500

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
