// ignore_for_file: no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:io';
import 'dart:math';

//import 'package:flutter/foundation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:file_picker/file_picker.dart';
import '../models/booking_model.dart';
import '../models/notification_model.dart';
import 'notification_services.dart';
import 'fcm_service.dart';
import 'notification_manager.dart';
import 'e_certificate_service.dart';
import 'station_service.dart';
import '../utils/app_logger.dart';

class BookingService {
  BookingService._();
  static final instance = BookingService._();

  final _firestore = FirebaseFirestore.instance;
  final _storage = FirebaseStorage.instance;
  final _notificationService = NotificationService();

  /// Check if user already has an active booking on the same date
  /// Returns true if an active (non-cancelled) booking exists for that date, false otherwise
  Future<bool> hasExistingBookingOnDate(
    String userId,
    DateTime trekDate,
  ) async {
    try {
      // Normalize the date to start of day (00:00:00)
      final startOfDay = DateTime(trekDate.year, trekDate.month, trekDate.day);
      final endOfDay = DateTime(
        trekDate.year,
        trekDate.month,
        trekDate.day,
        23,
        59,
        59,
      );

      final snapshot = await _firestore
          .collection('bookings')
          .where('userId', isEqualTo: userId)
          .where(
            'trekDate',
            isGreaterThanOrEqualTo: Timestamp.fromDate(startOfDay),
          )
          .where('trekDate', isLessThanOrEqualTo: Timestamp.fromDate(endOfDay))
          .get();

      // Filter out cancelled bookings
      final activeBookings = snapshot.docs.where((doc) {
        final status = doc['status']?.toString().toLowerCase() ?? '';
        return status != 'cancelled' && status != 'cancel';
      }).toList();

      return activeBookings.isNotEmpty;
    } catch (e) {
      AppLogger.e('Error checking for existing bookings: $e');
      rethrow;
    }
  }

  /// Get server timestamp for consistent time across clients
  Future<DateTime> getServerTimestamp() async {
    final doc = await _firestore.collection('_metadata').doc('timestamp').get();
    if (doc.exists) {
      final timestamp = doc['timestamp'] as Timestamp?;
      if (timestamp != null) {
        return timestamp.toDate();
      }
    }
    return DateTime.now();
  }

  /// Create a booking document and return its generated id
  /// Validates that user doesn't already have a booking on the same date
  Future<String> createBooking(BookingModel booking) async {
    // Check for duplicate bookings on the same date
    final hasDuplicateBooking = await hasExistingBookingOnDate(
      booking.userId,
      booking.trekDate.toDate(),
    );

    if (hasDuplicateBooking) {
      throw Exception(
        'You already have a booking on this date. Please choose a different date or cancel your existing booking.',
      );
    }

    final data = booking.toMap();
    // Remove id if present so Firestore generates one
    data.remove('id');
    final docRef = await _firestore.collection('bookings').add(data);

    // Send booking created notification
    final bookingId = docRef.id;
    try {
      final notification = NotificationModel(
        id: '', // Will be generated by Firestore
        title: 'Booking Submitted ✓',
        message: 'Your trek booking has been submitted and is under review.',
        type: NotificationType.success,
        timestamp: DateTime.now(),
        isRead: false,
        actionType: 'booking',
        actionData: bookingId,
      );

      await _notificationService.sendNotificationForUser(
        booking.userId,
        notification,
      );

      // Show in-app banner notification
      NotificationManager.showSuccess(
        title: 'Booking Submitted ✓',
        message: 'Your trek booking has been submitted and is under review.',
      );

      // Send FCM push notification
      await FCMService().sendNotificationToUser(
        targetUserId: booking.userId,
        title: 'Booking Submitted ✓',
        message: 'Your trek booking has been submitted and is under review.',
        actionType: 'booking_pending',
        actionData: bookingId,
      );
    } catch (e) {
      // Log error but don't fail the booking creation
      AppLogger.i('Failed to send booking created notification: $e');
    }

    return bookingId;
  }

  /// Update editable booking fields (typically user-provided info)
  Future<void> updateBooking(
    String bookingId, {
    String? affiliation,
    String? trekType,
    String? hometown,
    String? phoneNumber,
    String? notes,
    bool resubmitDeclined = false,
  }) async {
    final updateData = <String, dynamic>{
      'updatedAt': FieldValue.serverTimestamp(),
    };
    if (affiliation != null) {
      updateData['affiliation'] = affiliation;
    }
    if (trekType != null) {
      updateData['trekType'] = trekType;
    }
    if (hometown != null) {
      updateData['hometown'] = hometown;
    }
    if (phoneNumber != null) {
      updateData['phoneNumber'] = phoneNumber;
    }
    // Allow clearing notes by sending null
    updateData['notes'] = notes;

    // If resubmitting a declined booking, reset status to pending and clear admin notes
    if (resubmitDeclined) {
      updateData['status'] = 'pending';
      updateData['adminNotes'] = null;
    }

    await _firestore.collection('bookings').doc(bookingId).update(updateData);
  }

  /// Update the primary contact's category
  Future<void> updatePrimaryContactCategory(
    String bookingId,
    String newCategory,
  ) async {
    try {
      final docRef = _firestore.collection('bookings').doc(bookingId);
      final doc = await docRef.get();

      if (!doc.exists) throw Exception('Booking not found');

      final data = doc.data() as Map<String, dynamic>;
      final membersList = (data['members'] as List<dynamic>?) ?? [];

      if (membersList.isNotEmpty) {
        // Update the first member's category (primary contact)
        final primaryMember = membersList[0] as Map<String, dynamic>;
        primaryMember['category'] = newCategory;

        // Update the document
        await docRef.update({
          'members': membersList,
          'updatedAt': FieldValue.serverTimestamp(),
        });
      }
    } catch (e) {
      AppLogger.e('Error updating primary contact category: $e');
      rethrow;
    }
  }

  /// Upload a PlatformFile to storage under bookings/{bookingId}/attachments/
  /// Returns Attachment metadata on success.
  Future<Attachment> uploadAttachment(
    String bookingId,
    PlatformFile file, {
    void Function(int, int)? onProgress,
    String? memberName,
  }) async {
    final rand = Random().nextInt(100000);
    final name =
        '${DateTime.now().millisecondsSinceEpoch}_${rand}_${file.name}';
    final path = 'bookings/$bookingId/attachments/$name';
    final ref = _storage.ref(path);

    UploadTask uploadTask;

    // Create metadata to avoid null pointer exceptions
    final metadata = SettableMetadata(
      contentType: file.extension != null
          ? _getMimeType(file.extension!)
          : 'application/octet-stream',
    );

    if (file.bytes != null) {
      // Prefer bytes (loaded with withData:true) — always in-memory, never stale
      uploadTask = ref.putData(file.bytes!, metadata);
    } else if (file.path != null) {
      uploadTask = ref.putFile(File(file.path!), metadata);
    } else {
      throw ArgumentError('File has neither path nor bytes');
    }

    if (onProgress != null) {
      uploadTask.snapshotEvents.listen((s) {
        onProgress(s.bytesTransferred, s.totalBytes);
      });
    }

    try {
      final snapshot = await uploadTask;
      final url = await ref.getDownloadURL();
      final meta = Attachment(
        storagePath: snapshot.ref.fullPath,
        downloadURL: url,
        fileName: file.name,
        mimeType: snapshot.metadata?.contentType,
        size: snapshot.totalBytes,
        uploadedAt: Timestamp.now(),
        memberName: memberName,
      );

      // Append metadata to booking doc with retry logic for reliability
      try {
        await _firestore
            .collection('bookings')
            .doc(bookingId)
            .update({
              'attachments': FieldValue.arrayUnion([meta.toMap()]),
              'updatedAt': FieldValue.serverTimestamp(),
            })
            .timeout(
              const Duration(seconds: 10),
              onTimeout: () => throw TimeoutException(
                'Firestore update timeout after 10 seconds',
              ),
            );
      } catch (e) {
        // Still rethrow so caller knows about the issue
        rethrow;
      }

      return meta;
    } catch (e) {
      rethrow;
    }
  }

  /// Helper to determine MIME type from file extension
  String _getMimeType(String extension) {
    final ext = extension.toLowerCase();
    switch (ext) {
      case 'pdf':
        return 'application/pdf';
      case 'docx':
        return 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
      case 'doc':
        return 'application/msword';
      case 'jpg':
      case 'jpeg':
        return 'image/jpeg';
      case 'png':
        return 'image/png';
      case 'gif':
        return 'image/gif';
      case 'webp':
        return 'image/webp';
      default:
        return 'application/octet-stream';
    }
  }

  Future<void> createBookingWithAttachments(
    BookingModel booking,
    List<PlatformFile> files, {
    void Function(int, int)? onProgress,
  }) async {
    final bookingId = await createBooking(booking);
    for (final f in files) {
      try {
        await uploadAttachment(bookingId, f, onProgress: onProgress);
      } catch (_) {
        // continue on individual file errors
      }
    }
  }

  Stream<List<BookingModel>> streamBookingsForUser(String uid) {
    return _firestore
        .collection('bookings')
        .where('userId', isEqualTo: uid)
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snap) => snap.docs.map((d) => BookingModel.fromDoc(d)).toList());
  }

  /// Start listening to booking status changes for notifications
  /// Call this when user logs in to monitor booking updates from admin
  void startBookingStatusListener(String userId) {
    final Map<String, String> _lastKnownStatus = {};

    _firestore
        .collection('bookings')
        .where('userId', isEqualTo: userId)
        .snapshots()
        .listen((snapshot) {
          for (final change in snapshot.docChanges) {
            if (change.type == DocumentChangeType.modified) {
              final booking = BookingModel.fromDoc(change.doc);
              final bookingId = booking.id;
              final currentStatus = booking.status;
              final previousStatus = _lastKnownStatus[bookingId];

              // Only send notification if status actually changed
              if (previousStatus != null && previousStatus != currentStatus) {
                _sendBookingStatusNotification(
                  userId: userId,
                  bookingId: bookingId,
                  status: currentStatus,
                  adminNotes: booking.adminNotes,
                );

                // When booking is approved, check and award certificates
                if (currentStatus.toLowerCase() == 'approved') {
                  _checkCertificatesOnBookingApproval(userId);
                }
              }

              _lastKnownStatus[bookingId] = currentStatus;
            } else if (change.type == DocumentChangeType.added) {
              // Track initial status for new bookings
              final booking = BookingModel.fromDoc(change.doc);
              _lastKnownStatus[booking.id] = booking.status;
            }
          }
        });
  }

  /// Check and award certificates when a booking is approved
  Future<void> _checkCertificatesOnBookingApproval(String userId) async {
    try {
      // Use singleton instance and set user
      StationService.instance.setCurrentUser(userId);

      // Ensure stations are loaded
      if (!StationService.instance.isLoaded) {
        await StationService.instance.loadStations();
      }

      final visitedStations = StationService.instance.getVisitedStations();

      if (visitedStations.isNotEmpty) {
        // Check if user is eligible for any certificates
        await ECertificateService.instance.checkAndAwardCertificate(
          visitedStations,
        );
      }
    } catch (e) {
      AppLogger.i('Failed to check certificates on booking approval: $e');
      // Don't fail - let the app continue normally
    }
  }

  Future<void> cancelBooking(String bookingId) async {
    await _firestore.collection('bookings').doc(bookingId).update({
      'status': 'cancelled',
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  /// Update booking status (for admin approval/decline) with notification
  Future<void> updateBookingStatus(
    String bookingId, {
    required String status,
    String? adminNotes,
  }) async {
    // Get booking to retrieve userId for notification
    final bookingDoc = await _firestore
        .collection('bookings')
        .doc(bookingId)
        .get();
    if (!bookingDoc.exists) {
      throw Exception('Booking not found');
    }

    final userId = bookingDoc.data()?['userId'] as String?;
    if (userId == null) {
      throw Exception('User ID not found in booking');
    }

    // Update booking status
    final updateData = <String, dynamic>{
      'status': status,
      'updatedAt': FieldValue.serverTimestamp(),
    };
    if (adminNotes != null) {
      updateData['adminNotes'] = adminNotes;
    }

    await _firestore.collection('bookings').doc(bookingId).update(updateData);

    // Send notification based on status
    await _sendBookingStatusNotification(
      userId: userId,
      bookingId: bookingId,
      status: status,
      adminNotes: adminNotes,
    );
  }

  /// Send notification when booking status changes
  Future<void> _sendBookingStatusNotification({
    required String userId,
    required String bookingId,
    required String status,
    String? adminNotes,
  }) async {
    String title;
    String message;
    NotificationType type;

    switch (status.toLowerCase()) {
      case 'approved':
        title = 'Booking Approved ✓';
        message =
            adminNotes ??
            'Your trek booking has been approved! Get ready for your adventure.';
        type = NotificationType.success;
        break;
      case 'declined':
      case 'rejected':
        title = 'Booking Declined';
        message =
            adminNotes ??
            'Your trek booking has been declined. Please contact support for more information.';
        type = NotificationType.alert;
        break;
      case 'pending':
        title = 'Booking Under Review';
        message = 'Your booking is being reviewed by our team.';
        type = NotificationType.info;
        break;
      case 'cancelled':
        title = 'Booking Cancelled';
        message = 'Your trek booking has been cancelled.';
        type = NotificationType.warning;
        break;
      default:
        title = 'Booking Status Updated';
        message =
            adminNotes ?? 'Your booking status has been updated to: $status';
        type = NotificationType.info;
    }

    final notification = NotificationModel(
      id: '', // Will be generated by Firestore
      title: title,
      message: message,
      type: type,
      timestamp: DateTime.now(),
      isRead: false,
      actionType: 'booking',
      actionData: bookingId,
    );

    try {
      await _notificationService.sendNotificationForUser(userId, notification);

      // Show in-app banner based on notification type
      if (type == NotificationType.success) {
        NotificationManager.showSuccess(title: title, message: message);
      } else if (type == NotificationType.alert) {
        NotificationManager.showError(title: title, message: message);
      } else if (type == NotificationType.warning) {
        NotificationManager.showWarning(title: title, message: message);
      } else {
        NotificationManager.showInfo(title: title, message: message);
      }

      // Also send FCM push notification
      String actionType;
      switch (status.toLowerCase()) {
        case 'approved':
          actionType = 'booking_approved';
          break;
        case 'declined':
        case 'rejected':
          actionType = 'booking_rejected';
          break;
        case 'pending':
          actionType = 'booking_pending';
          break;
        case 'cancelled':
          actionType = 'booking_cancelled';
          break;
        default:
          actionType = 'booking_updated';
      }

      await FCMService().sendNotificationToUser(
        targetUserId: userId,
        title: title,
        message: message,
        actionType: actionType,
        actionData: bookingId,
      );
    } catch (e) {
      // Log error but don't fail the booking update
      AppLogger.i('Failed to send booking notification: $e');
    }
  }

  /// Delete an attachment from both Storage and Firestore
  Future<void> deleteAttachment(String bookingId, Attachment attachment) async {
    try {
      // Delete from Storage
      final storageRef = _storage.ref(attachment.storagePath);
      await storageRef.delete();

      // Remove from Firestore
      await _firestore.collection('bookings').doc(bookingId).update({
        'attachments': FieldValue.arrayRemove([attachment.toMap()]),
        'updatedAt': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      AppLogger.i('ERROR deleting attachment: $e');
      rethrow;
    }
  }
}
