// File generated by FlutterFire CLI.
// This file is platform-specific and should be generated using flutterfire configure
// For now, we'll create a basic version that you'll need to update after running flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions has not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions has not been configured for ${defaultTargetPlatform.name} - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr-3aDayxiHaRjbQoJ6wll1QRTvCoPAf8',
    appId: '1:431638508645:web:ad5f1ebd7e4c942baf028c',
    messagingSenderId: '431638508645',
    projectId: 'trekscanplus',
    authDomain: 'trekscanplus.firebaseapp.com',
    storageBucket: 'trekscanplus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEVhCzB7gY6ubvCXcJ_8svmINIDs_RyTo',
    appId: '1:431638508645:android:764c90e43cdee6e6af028c',
    messagingSenderId: '431638508645',
    projectId: 'trekscanplus',
    storageBucket: 'trekscanplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyupYL4JzTuoJwfZVUrXg0CVnvR-UiEs',
    appId: '1:431638508645:ios:9b13fb5ea96dfbd1af028c',
    messagingSenderId: '431638508645',
    projectId: 'trekscanplus',
    storageBucket: 'trekscanplus.firebasestorage.app',
    iosBundleId: 'com.example.hamiguitanTrekscanPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyupYL4JzTuoJwfZVUrXg0CVnvR-UiEs',
    appId: '1:431638508645:ios:9b13fb5ea96dfbd1af028c',
    messagingSenderId: '431638508645',
    projectId: 'trekscanplus',
    storageBucket: 'trekscanplus.firebasestorage.app',
    iosBundleId: 'com.example.hamiguitanTrekscanPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr-3aDayxiHaRjbQoJ6wll1QRTvCoPAf8',
    appId: '1:431638508645:web:e0f2a3491880bd4daf028c',
    messagingSenderId: '431638508645',
    projectId: 'trekscanplus',
    authDomain: 'trekscanplus.firebaseapp.com',
    storageBucket: 'trekscanplus.firebasestorage.app',
  );

}